### ISSUE TITLE
Scrutinizer CI

### ISSUE THREAD

**Issue by rtheunissen** [thephpleague/oauth2-client#405]
With a few recent documentation and code style discussions, I believe it would be valuable to use Scrutinizer CI. Unfortunately I don't have admin access to the repo so someone else will need to get it going. @ramsey 

This is the .scrutinizer.yml file that I've used in the past, which I believe will be a good starting point.

```
filter:
    excluded_paths:
        - 'test/*'

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
```
